run:
  timeout: 1m
  tests: false

linters-settings:
  goconst:
    min-len: 5
    min-occurrences: 4
  misspell:
    locale: US
  revive:
    rules:
      - name: exported

linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
