before:
  hooks:
    - go mod download
builds:
  - goos: [linux, darwin, windows]
    goarch: [386, amd64, arm, arm64]
    flags:
      - "-a"
    ldflags:
      - '-extldflags "-static"'
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser
    env:
      - CGO_ENABLED=0
    main: ./cmd/go-fsm/main.go
    binary: go-fsm

archives:
  - wrap_in_directory: true
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
